In [ ]:
# import the ECC dataset
import pandas as pd

In [ ]:
df = pd.read_csv('/home/sbourgeat/Project/Results_ECC/homology2voxel_pairwise/persistence_entropy_100_female.csv')

In [3]:
# Assuming df is your DataFrame and 'ecc' is the name of the column
df['ecc'] = df['ecc'].apply(lambda x: [float(num) for num in x.strip('[\n ]').split()])

# Print the transformed DataFrame
print(df)

     cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
0            61   NaN   NaN   NaN               0               0
1            66   NaN   NaN   NaN               0               0
2            89   NaN   NaN   NaN               0               0
3            90   NaN   NaN   NaN               0               0
4           166   NaN   NaN   NaN               0               0
..          ...   ...   ...   ...             ...             ...
569        3467   NaN   NaN   NaN               0               0
570        3487   NaN   NaN   NaN               0               0
571        3497   NaN   NaN   NaN               0               0
572        3499   NaN   NaN   NaN               0               0
573        3510   NaN   NaN   NaN               0               0

     alpha_entropy2                                                ecc  \
0                 0  [2.0, 2.0, -2.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0,...
1                 0  [-25.0, -25.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
2                 0  [-21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21...
3                 0  [-1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
4                 0  [-11.0, -11.0, -11.0, 4.0, 4.0, 1.0, 1.0, 1.0,...
..              ...                                                ...
569               0  [6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
570               0  [6.0, 2.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
571               0  [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...
572               0  [8.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
573               0  [2.0, 2.0, 2.0, 2.0, -1.0, -1.0, -1.0, 0.0, 1....

     cluster_size
0              30
1              46
2              27
3              16
4              20
..            ...
569            26
570             7
571            13
572            10
573             9

[574 rows x 9 columns]

In [4]:
match = pd.read_csv('/home/sbourgeat/Project/matched_coords/matched_points.csv')

In [5]:
match['file'][0]

'/home/samuel/brainMorpho/Analysis_results/rotated_coords/coordinates_131_male.csv'

In [6]:
import os
import pandas as pd
from sklearn.cross_decomposition import CCA
from sklearn.preprocessing import StandardScaler

In [7]:
# Function to extract genotype number and sex from file name
def extract_genotype_info(file_name):
    genotype_info = file_name.split('.')[0].split('_')
    genotype_number = "DGRP_" + genotype_info[-2]  # Assuming genotype is the second-to-last element
    sex = genotype_info[-1]
    if sex == "male":
        sex = "M"
    elif sex == "female":
        sex = "F"
    return genotype_number, sex

# Read ECC data for each genotype from files in a folder and combine into a single DataFrame
folder_path = "/home/sbourgeat/Project/Results_ECC/homology2voxel_pairwise/"
genotype_data = []
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)
        genotype_number, sex = extract_genotype_info(file_name)
        genotype_df = pd.read_csv(file_path)  # Assuming CSV files have ECC data
        genotype_df['ecc'] = genotype_df['ecc'].apply(lambda x: [float(num) for num in x.strip('[\n ]').split()])# format the ecc col
        genotype_df['DGRP'] = genotype_number  # Add genotype number as a column
        genotype_df['sex'] = sex  # Add sex as a column
        genotype_data.append(genotype_df)

In [8]:
genotype_data

[     cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            10   NaN   NaN   NaN               0               0
 1           156   NaN   NaN   NaN               0               0
 2           161   NaN   NaN   NaN               0               0
 3           178   NaN   NaN   NaN               0               0
 4           188   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 788        3781   NaN   NaN   NaN               0               0
 789        3787   NaN   NaN   NaN               0               0
 790        3802   NaN   NaN   NaN               0               0
 791        3813   NaN   NaN   NaN               0               0
 792        3820   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [-172.0, -172.0, 70.0, 2.0, 0.0, -1.0, -4.0, -...
 1                 0  [8.0, 8.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...
 2                 0  [-2.0, -2.0, -2.0, -2.0, -6.0, -6.0, 2.0, 1.0,...
 3                 0  [8.0, 8.0, 8.0, 8.0, 8.0, -1.0, -1.0, -1.0, 3....
 4                 0  [13.0, -6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 ..              ...                                                ...
 788               0  [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...
 789               0  [4.0, -1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 790               0  [9.0, 9.0, 9.0, 9.0, 1.0, 1.0, 3.0, 2.0, 2.0, ...
 791               0  [-1.0, -4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 792               0  [-13.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...

      cluster_size      DGRP sex
 0             234  DGRP_309   M
 1               9  DGRP_309   M
 2              20  DGRP_309   M
 3              10  DGRP_309   M
 4              22  DGRP_309   M
 ..            ...       ...  ..
 788             6  DGRP_309   M
 789            13  DGRP_309   M
 790            11  DGRP_309   M
 791            17  DGRP_309   M
 792            43  DGRP_309   M

 [793 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0             7   NaN   NaN   NaN               0               0
 1            37   NaN   NaN   NaN               0               0
 2           121   NaN   NaN   NaN               0               0
 3           151   NaN   NaN   NaN               0               0
 4           211   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 349        2576   NaN   NaN   NaN               0               0
 350        2577   NaN   NaN   NaN               0               0
 351        2582   NaN   NaN   NaN               0               0
 352        2589   NaN   NaN   NaN               0               0
 353        2595   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [5.0, 5.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...
 1                 0  [-32.0, -32.0, 0.0, 3.0, 2.0, 1.0, 1.0, 1.0, 1...
 2                 0  [-75.0, -75.0, -75.0, -75.0, 11.0, 11.0, 28.0,...
 3                 0  [-41.0, -41.0, -41.0, -41.0, -41.0, -41.0, -41...
 4                 0  [-72.0, 11.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1....
 ..              ...                                                ...
 349               0  [-13.0, -13.0, -13.0, 2.0, 2.0, 1.0, 1.0, 1.0,...
 350               0  [-13.0, -13.0, 4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
 351               0  [4.0, -4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 352               0  [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, ...
 353               0  [6.0, 6.0, 6.0, 6.0, -4.0, -4.0, 0.0, 0.0, 0.0...

      cluster_size     DGRP sex
 0              16  DGRP_48   M
 1              62  DGRP_48   M
 2              90  DGRP_48   M
 3              54  DGRP_48   M
 4              93  DGRP_48   M
 ..            ...      ...  ..
 349            26  DGRP_48   M
 350            26  DGRP_48   M
 351            12  DGRP_48   M
 352             8  DGRP_48   M
 353            15  DGRP_48   M

 [354 rows x 11 columns],
       cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0             38   NaN   NaN   NaN               0               0
 1             53   NaN   NaN   NaN               0               0
 2             59   NaN   NaN   NaN               0               0
 3             75   NaN   NaN   NaN               0               0
 4            101   NaN   NaN   NaN               0               0
 ...          ...   ...   ...   ...             ...             ...
 1044        5424   NaN   NaN   NaN               0               0
 1045        5431   NaN   NaN   NaN               0               0
 1046        5457   NaN   NaN   NaN               0               0
 1047        5461   NaN   NaN   NaN               0               0
 1048        5477   NaN   NaN   NaN               0               0

       alpha_entropy2                                                ecc  \
 0                  0  [5.0, 5.0, -2.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0,...
 1                  0  [-3.0, -3.0, -3.0, -3.0, 0.0, 0.0, 2.0, 1.0, 1...
 2                  0  [-9.0, -9.0, -9.0, -9.0, 0.0, 0.0, 5.0, 1.0, 1...
 3                  0  [-1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 4                  0  [-7.0, 6.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 ...              ...                                                ...
 1044               0  [7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 4.0, 4.0, ...
 1045               0  [6.0, 6.0, 4.0, 4.0, 4.0, 3.0, 3.0, 3.0, 3.0, ...
 1046               0  [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...
 1047               0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1048               0  [4.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...

       cluster_size     DGRP sex
 0               17  DGRP_59   F
 1               15  DGRP_59   F
 2               21  DGRP_59   F
 3               18  DGRP_59   F
 4               26  DGRP_59   F
 ...            ...      ...  ..
 1044            14  DGRP_59   F
 1045            13  DGRP_59   F
 1046             8  DGRP_59   F
 1047             5  DGRP_59   F
 1048            16  DGRP_59   F

 [1049 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            13   NaN   NaN   NaN               0               0
 1            15   NaN   NaN   NaN               0               0
 2            34   NaN   NaN   NaN               0               0
 3            54   NaN   NaN   NaN               0               0
 4            57   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 725        4483   NaN   NaN   NaN               0               0
 726        4507   NaN   NaN   NaN               0               0
 727        4531   NaN   NaN   NaN               0               0
 728        4534   NaN   NaN   NaN               0               0
 729        4538   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [0.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1                 0  [0.0, 0.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, ...
 2                 0  [-29.0, 6.0, 0.0, -1.0, -2.0, -3.0, 1.0, 1.0, ...
 3                 0  [7.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 4                 0  [3.0, 3.0, 3.0, 2.0, 2.0, 0.0, -1.0, -1.0, 0.0...
 ..              ...                                                ...
 725               0  [12.0, 7.0, 3.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0,...
 726               0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 727               0  [-8.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 728               0  [10.0, 1.0, 4.0, 3.0, 3.0, 3.0, 2.0, 1.0, 1.0,...
 729               0  [10.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...

      cluster_size      DGRP sex
 0              29  DGRP_900   M
 1              19  DGRP_900   M
 2             123  DGRP_900   M
 3              13  DGRP_900   M
 4              16  DGRP_900   M
 ..            ...       ...  ..
 725            17  DGRP_900   M
 726             8  DGRP_900   M
 727            26  DGRP_900   M
 728            16  DGRP_900   M
 729            12  DGRP_900   M

 [730 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0             4   NaN   NaN   NaN               0               0
 1            13   NaN   NaN   NaN               0               0
 2            16   NaN   NaN   NaN               0               0
 3            32   NaN   NaN   NaN               0               0
 4            37   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 858        4820   NaN   NaN   NaN               0               0
 859        4829   NaN   NaN   NaN               0               0
 860        4834   NaN   NaN   NaN               0               0
 861        4844   NaN   NaN   NaN               0               0
 862        4852   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1                 0  [11.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 2                 0  [5.0, 5.0, 5.0, 5.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...
 3                 0  [-23.0, 2.0, 2.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0...
 4                 0  [1.0, 3.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, ...
 ..              ...                                                ...
 858               0  [5.0, 5.0, 4.0, 0.0, -1.0, 0.0, 1.0, 1.0, 1.0,...
 859               0  [4.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 860               0  [7.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 861               0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 862               0  [8.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...

      cluster_size      DGRP sex
 0              22  DGRP_802   M
 1              15  DGRP_802   M
 2               7  DGRP_802   M
 3              87  DGRP_802   M
 4              60  DGRP_802   M
 ..            ...       ...  ..
 858            14  DGRP_802   M
 859             5  DGRP_802   M
 860             9  DGRP_802   M
 861            12  DGRP_802   M
 862            11  DGRP_802   M

 [863 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            13   NaN   NaN   NaN               0               0
 1            38   NaN   NaN   NaN               0               0
 2            54   NaN   NaN   NaN               0               0
 3            91   NaN   NaN   NaN               0               0
 4           119   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 847        4618   NaN   NaN   NaN               0               0
 848        4621   NaN   NaN   NaN               0               0
 849        4624   NaN   NaN   NaN               0               0
 850        4630   NaN   NaN   NaN               0               0
 851        4631   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1                 0  [-92.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 2                 0  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...
 3                 0  [-397.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1....
 4                 0  [-74.0, 1.0, 3.0, 1.0, 2.0, 1.0, 2.0, 0.0, -2....
 ..              ...                                                ...
 847               0  [8.0, 8.0, 8.0, 5.0, 5.0, 5.0, 5.0, 3.0, 3.0, ...
 848               0  [7.0, 4.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, ...
 849               0  [-4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4....
 850               0  [7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, ...
 851               0  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 1.0, 1.0, ...

      cluster_size     DGRP sex
 0              52  DGRP_26   M
 1             186  DGRP_26   M
 2               7  DGRP_26   M
 3             555  DGRP_26   M
 4             123  DGRP_26   M
 ..            ...      ...  ..
 847            11  DGRP_26   M
 848             8  DGRP_26   M
 849            11  DGRP_26   M
 850            13  DGRP_26   M
 851            10  DGRP_26   M

 [852 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            34   NaN   NaN   NaN               0               0
 1            46   NaN   NaN   NaN               0               0
 2            49   NaN   NaN   NaN               0               0
 3            85   NaN   NaN   NaN               0               0
 4            96   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 920        4703   NaN   NaN   NaN               0               0
 921        4720   NaN   NaN   NaN               0               0
 922        4731   NaN   NaN   NaN               0               0
 923        4743   NaN   NaN   NaN               0               0
 924        4787   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [-2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 1                 0  [3.0, 3.0, 2.0, 3.0, 2.0, 1.0, 2.0, 0.0, 1.0, ...
 2                 0  [6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 3                 0  [15.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 4                 0  [-4.0, 0.0, 2.0, 2.0, 0.0, 1.0, 1.0, 1.0, 1.0,...
 ..              ...                                                ...
 920               0  [-3.0, -4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 921               0  [4.0, 4.0, 4.0, 1.0, 1.0, 0.0, 0.0, 0.0, -1.0,...
 922               0  [6.0, 5.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 923               0  [3.0, 3.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 924               0  [5.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...

      cluster_size     DGRP sex
 0              28  DGRP_75   F
 1              29  DGRP_75   F
 2              11  DGRP_75   F
 3              35  DGRP_75   F
 4              31  DGRP_75   F
 ..            ...      ...  ..
 920            25  DGRP_75   F
 921            14  DGRP_75   F
 922             8  DGRP_75   F
 923             7  DGRP_75   F
 924            18  DGRP_75   F

 [925 rows x 11 columns],
       cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0             37   NaN   NaN   NaN               0               0
 1             39   NaN   NaN   NaN               0               0
 2             41   NaN   NaN   NaN               0               0
 3             50   NaN   NaN   NaN               0               0
 4             54   NaN   NaN   NaN               0               0
 ...          ...   ...   ...   ...             ...             ...
 1080        4643   NaN   NaN   NaN               0               0
 1081        4653   NaN   NaN   NaN               0               0
 1082        4657   NaN   NaN   NaN               0               0
 1083        4661   NaN   NaN   NaN               0               0
 1084        4668   NaN   NaN   NaN               0               0

       alpha_entropy2                                                ecc  \
 0                  0  [1.0, 1.0, 3.0, 4.0, 2.0, 0.0, 2.0, 2.0, 2.0, ...
 1                  0  [-10.0, -10.0, -10.0, -10.0, -10.0, -10.0, 1.0...
 2                  0  [-1.0, -1.0, -1.0, -2.0, 0.0, 1.0, 1.0, 1.0, 1...
 3                  0  [-4.0, -4.0, -4.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1....
 4                  0  [-17.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 ...              ...                                                ...
 1080               0  [3.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1081               0  [2.0, 2.0, -3.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0,...
 1082               0  [8.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1083               0  [6.0, 4.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 1084               0  [3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, ...

       cluster_size      DGRP sex
 0               14  DGRP_332   F
 1               23  DGRP_332   F
 2               15  DGRP_332   F
 3               15  DGRP_332   F
 4               41  DGRP_332   F
 ...            ...       ...  ..
 1080            19  DGRP_332   F
 1081            15  DGRP_332   F
 1082            13  DGRP_332   F
 1083            12  DGRP_332   F
 1084             8  DGRP_332   F

 [1085 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            14   NaN   NaN   NaN               0               0
 1            21   NaN   NaN   NaN               0               0
 2            40   NaN   NaN   NaN               0               0
 3            55   NaN   NaN   NaN               0               0
 4            56   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 451        3112   NaN   NaN   NaN               0               0
 452        3113   NaN   NaN   NaN               0               0
 453        3116   NaN   NaN   NaN               0               0
 454        3118   NaN   NaN   NaN               0               0
 455        3129   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [3.0, -4.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
 1                 0  [5.0, 3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 1.0, 1.0, ...
 2                 0  [-6.0, -6.0, -6.0, -6.0, 3.0, 3.0, 4.0, 4.0, 2...
 3                 0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
 4                 0  [-1.0, -1.0, -1.0, -1.0, 0.0, 0.0, 2.0, 1.0, 1...
 ..              ...                                                ...
 451               0  [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...
 452               0  [-3.0, -3.0, -3.0, -3.0, -1.0, -1.0, 1.0, 1.0,...
 453               0  [-4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -2.0, -2....
 454               0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
 455               0  [10.0, 10.0, -5.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1....

      cluster_size      DGRP sex
 0              25  DGRP_335   F
 1              10  DGRP_335   F
 2              16  DGRP_335   F
 3               9  DGRP_335   F
 4              17  DGRP_335   F
 ..            ...       ...  ..
 451             6  DGRP_335   F
 452            15  DGRP_335   F
 453            22  DGRP_335   F
 454            12  DGRP_335   F
 455            12  DGRP_335   F

 [456 rows x 11 columns],
      cluster_id  pe_0  pe_1  pe_2  alpha_entropy0  alpha_entropy1  \
 0            23   NaN   NaN   NaN               0               0
 1            40   NaN   NaN   NaN               0               0
 2            47   NaN   NaN   NaN               0               0
 3            63   NaN   NaN   NaN               0               0
 4            74   NaN   NaN   NaN               0               0
 ..          ...   ...   ...   ...             ...             ...
 737        3843   NaN   NaN   NaN               0               0
 738        3861   NaN   NaN   NaN               0               0
 739        3863   NaN   NaN   NaN               0               0
 740        3865   NaN   NaN   NaN               0               0
 741        3884   NaN   NaN   NaN               0               0

      alpha_entropy2                                                ecc  \
 0                 0  [11.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,...
 1                 0  [-6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6....

In [9]:

# Combine ECC data into a single DataFrame
combined_data = pd.concat(genotype_data, ignore_index=True)

In [10]:
combined_data 
# Add Coordinates of the clusters

,cluster_id,pe_0,pe_1,pe_2,alpha_entropy0,alpha_entropy1,alpha_entropy2,ecc,cluster_size,DGRP,sex
0,10,NaN,NaN,NaN,0,0,0,"[-172.0, -172.0, 70.0, 2.0, 0.0, -1.0, -4.0, -...",234,DGRP_309,M
1,156,NaN,NaN,NaN,0,0,0,"[8.0, 8.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...",9,DGRP_309,M
2,161,NaN,NaN,NaN,0,0,0,"[-2.0, -2.0, -2.0, -2.0, -6.0, -6.0, 2.0, 1.0,...",20,DGRP_309,M
3,178,NaN,NaN,NaN,0,0,0,"[8.0, 8.0, 8.0, 8.0, 8.0, -1.0, -1.0, -1.0, 3....",10,DGRP_309,M
4,188,NaN,NaN,NaN,0,0,0,"[13.0, -6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...",22,DGRP_309,M
...,...,...,...,...,...,...,...,...,...,...,...
82972,4118,NaN,NaN,NaN,0,0,0,"[4.0, 4.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0,...",10,DGRP_843,M
82973,4138,NaN,NaN,NaN,0,0,0,"[-2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2....",13,DGRP_843,M
82974,4161,NaN,NaN,NaN,0,0,0,"[-9.0, -9.0, -9.0, -4.0, -4.0, 1.0, 1.0, 1.0, ...",33,DGRP_843,M
82975,4183,NaN,NaN,NaN,0,0,0,"[-4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4.0, -4....",12,DGRP_843,M
82976,4221,NaN,NaN,NaN,0,0,0,"[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, ...",8,DGRP_843,M

In [11]:
behav = pd.read_csv("dgrpool_kl_behaviour.tsv",sep = '\t')

In [12]:
all_data = pd.merge(combined_data, behav, on=["DGRP", "sex"])

In [13]:
all_data

,cluster_id,pe_0,pe_1,pe_2,alpha_entropy0,alpha_entropy1,alpha_entropy2,ecc,cluster_size,DGRP,...,LSM_frac,LSM_frac_se,LSM_ls,LSM_ls_se,KL_frac,KL_ls,en_s_frac,en_ns_frac,en_s_ls,en_ns_ls
0,10,NaN,NaN,NaN,0,0,0,"[-172.0, -172.0, 70.0, 2.0, 0.0, -1.0, -4.0, -...",234,DGRP_309,...,0.036524,0.030042,-0.181848,0.523066,0.711294,0.137173,0.803315,0.673012,1.212314,1.461472
1,156,NaN,NaN,NaN,0,0,0,"[8.0, 8.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...",9,DGRP_309,...,0.036524,0.030042,-0.181848,0.523066,0.711294,0.137173,0.803315,0.673012,1.212314,1.461472
2,161,NaN,NaN,NaN,0,0,0,"[-2.0, -2.0, -2.0, -2.0, -6.0, -6.0, 2.0, 1.0,...",20,DGRP_309,...,0.036524,0.030042,-0.181848,0.523066,0.711294,0.137173,0.803315,0.673012,1.212314,1.461472
3,178,NaN,NaN,NaN,0,0,0,"[8.0, 8.0, 8.0, 8.0, 8.0, -1.0, -1.0, -1.0, 3....",10,DGRP_309,...,0.036524,0.030042,-0.181848,0.523066,0.711294,0.137173,0.803315,0.673012,1.212314,1.461472
4,188,NaN,NaN,NaN,0,0,0,"[13.0, -6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...",22,DGRP_309,...,0.036524,0.030042,-0.181848,0.523066,0.711294,0.137173,0.803315,0.673012,1.212314,1.461472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40885,3662,NaN,NaN,NaN,0,0,0,"[7.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",13,DGRP_354,...,0.012205,0.031416,-0.029800,0.533372,0.031584,0.250158,0.986899,1.126929,1.407532,1.473502
40886,3668,NaN,NaN,NaN,0,0,0,"[-3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3....",14,DGRP_354,...,0.012205,0.031416,-0.029800,0.533372,0.031584,0.250158,0.986899,1.126929,1.407532,1.473502
40887,3669,NaN,NaN,NaN,0,0,0,"[8.0, 8.0, 2.0, 3.0, 2.0, 3.0, 3.0, 0.0, 1.0, ...",12,DGRP_354,...,0.012205,0.031416,-0.029800,0.533372,0.031584,0.250158,0.986899,1.126929,1.407532,1.473502
40888,3683,NaN,NaN,NaN,0,0,0,"[6.0, 6.0, 5.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0, ...",7,DGRP_354,...,0.012205,0.031416,-0.029800,0.533372,0.031584,0.250158,0.986899,1.126929,1.407532,1.473502
40889,3701,NaN,NaN,NaN,0,0,0,"[-6.0, -6.0, -6.0, -6.0, 1.0, 1.0, 4.0, 1.0, 1...",17,DGRP_354,...,0.012205,0.031416,-0.029800,0.533372,0.031584,0.250158,0.986899,1.126929,1.407532,1.473502

In [14]:
# Assuming your DataFrame is named all_data
# Group by 'Genotype' and calculate the sum of 'ecc' for each group
all_data['ecc']

0        [-172.0, -172.0, 70.0, 2.0, 0.0, -1.0, -4.0, -...
1        [8.0, 8.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 0.0, ...
2        [-2.0, -2.0, -2.0, -2.0, -6.0, -6.0, 2.0, 1.0,...
3        [8.0, 8.0, 8.0, 8.0, 8.0, -1.0, -1.0, -1.0, 3....
4        [13.0, -6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0...
                               ...
40885    [7.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
40886    [-3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0, -3....
40887    [8.0, 8.0, 2.0, 3.0, 2.0, 3.0, 3.0, 0.0, 1.0, ...
40888    [6.0, 6.0, 5.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0, ...
40889    [-6.0, -6.0, -6.0, -6.0, 1.0, 1.0, 4.0, 1.0, 1...
Name: ecc, Length: 40890, dtype: object

In [16]:
c = pd.read_csv('/home/sbourgeat/Project/Results_ECC/rotated_coords/coordinates_100_female.csv')
c

,cluster_id,coordinate_x,coordinate_y,coordinate_z,distance,direction_x,direction_y,direction_z
0,3225,1.158059,-0.006121,-1.737923,1.814548,0.546363,-0.032379,-0.836922
1,1458,-1.938409,-0.533972,-0.042034,2.192446,-0.960144,-0.267557,0.080848
2,2094,0.237299,-0.784169,-1.333713,1.395410,0.050625,-0.599681,-0.798636
3,2267,0.361163,-0.235674,-1.100184,0.947064,0.205378,-0.304420,-0.930133
4,3037,-1.319846,-0.593777,-0.254418,1.621347,-0.916832,-0.398686,-0.021667
...,...,...,...,...,...,...,...,...
561,1480,-1.476372,-0.120647,0.342354,1.744996,-0.941566,-0.099300,0.321858
562,2537,-0.198502,0.270656,-0.012562,0.472875,-0.772209,0.461062,0.437167
563,1702,0.428985,-0.219397,-1.084811,0.944429,0.277765,-0.288035,-0.916451
564,1293,-1.265631,-1.092006,-0.863022,1.943202,-0.737076,-0.589047,-0.331275
565,3226,-1.734743,-1.548716,0.526521,2.595354,-0.732617,-0.617005,0.287363

In [17]:
# Function to extract genotype number and sex from file name
def extract_genotype_info(file_name):
    genotype_info = file_name.split('.')[0].split('_')
    genotype_number = "DGRP_" + genotype_info[-2]  # Assuming genotype is the second-to-last element
    sex = genotype_info[-1]
    if sex == "male":
        sex = "M"
    elif sex == "female":
        sex = "F"
    return genotype_number, sex

# Read data for each genotype from files in a folder and combine into a single DataFrame
folder_path = "/home/sbourgeat/Project/Results_ECC/rotated_coords/"
genotype_data = []
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)
        genotype_number, sex = extract_genotype_info(file_name)
        genotype_df = pd.read_csv(file_path)  # Assuming CSV files have data
        genotype_df['DGRP'] = genotype_number  # Add genotype number as a column
        genotype_df['sex'] = sex  # Add sex as a column
        genotype_data.append(genotype_df)

In [19]:
combined_coords = pd.concat(genotype_data, ignore_index=True)
combined_coords

,cluster_id,coordinate_x,coordinate_y,coordinate_z,distance,direction_x,direction_y,direction_z,DGRP,sex
0,949,1.630753,1.833270,-0.288597,2.821683,0.422278,0.887508,-0.184420,DGRP_486,M
1,2216,0.484251,2.273698,-0.575405,3.053654,0.014747,0.964319,-0.264334,DGRP_486,M
2,1316,-0.739346,1.651889,-0.645712,2.748600,-0.428787,0.845116,-0.319250,DGRP_486,M
3,2373,-0.715524,1.330322,-0.635248,2.467882,-0.467908,0.810946,-0.351324,DGRP_486,M
4,1731,-0.087904,2.057680,-1.167995,3.111736,-0.169398,0.876899,-0.449837,DGRP_486,M
...,...,...,...,...,...,...,...,...,...,...
43894,1992,-0.280935,2.639285,-0.721975,3.225283,-0.256770,0.948687,-0.184559,DGRP_365,F
43895,1530,-1.010804,0.881065,1.614646,2.674671,-0.582511,0.486626,0.651058,DGRP_365,F
43896,4631,0.364662,1.793215,1.952480,3.042521,-0.060002,0.727593,0.683380,DGRP_365,F
43897,2324,-1.689104,0.638000,1.798919,3.135228,-0.713289,0.337615,0.614194,DGRP_365,F
43898,780,-0.231930,0.592235,3.198381,3.562163,-0.218730,0.284304,0.933450,DGRP_365,F

In [20]:
# merge all_data and combined coords

full_df = pd.merge(all_data, combined_coords, on=["DGRP", "sex","cluster_id"])

In [ ]:
full_df['ecc'].sum()

In [26]:
from sklearn.cross_decomposition import CCA
import pandas as pd
import numpy as np

# Assuming df is your DataFrame with columns: 'Volume', 'alpha_entropy0', 'alpha_entropy1', 'alpha_entropy2', 
# 'Entropy0', 'Entropy1', 'Entropy2'

# Extract relevant columns
X = full_df['ecc'].max()  # 'alpha_entropies'
Y = full_df['KL_ls']

# Initialize CCA model
cca = CCA(n_components=1)

# Fit the model
cca.fit(X, Y)

# Transform the data to canonical variables
canonical_X, canonical_Y = cca.transform(X, Y)

# Get canonical coefficients for Volume
canonical_coefficients = cca.coef_

# Display the canonical coefficients for Volume
print("Canonical Coefficients for KL:")
print(canonical_coefficients)

ValueError: Found input variables with inconsistent numbers of samples: [200, 15770]